version: '3'

vars:
  APPNAME: myapiserver
  VERSION:
    sh: git describe --tags --always --dirty="-dev"
  IMGNAME: ghcr.io/ericslandry/{{.APPNAME}}:{{.VERSION}}

tasks:
  build:
    cmds:
      - go generate ./api/api.go
      - go build -ldflags "-w -X main.version={{.VERSION}}" -o bin/{{.APPNAME}} ./cmd/{{.APPNAME}}

  docker-build:
    cmds:
      - task: build
      - docker buildx build . -t {{.IMGNAME}} --build-arg APPNAME={{.APPNAME}}

  docker-push:
    cmds:
      - task: docker-build
      - docker push {{.IMGNAME}}

  clean:
    cmds:
      - rm -rf bin

  test:
    cmds:
      - go test -v ./...

  run:
    cmds:
      - go run ./cmd/{{.APPNAME}}

  kill:
    cmds:
      - pkill {{.APPNAME}}

  default:
    desc: "Build and Test"
    cmds:
      - task: build
      - task: test
