# This workflow builds a docker image with the Dev Container CLI
#
name: Publish Docker image to GitHub Container Registry

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push docker image using devcontainer
      uses: devcontainers/ci@v0.3
      with:
        cacheFrom: ghcr.io/${{ github.repository }}-devcontainer
        runCmd: GHCR_USER=${{ github.repository_owner }} GHCR_TOKEN=${{ secrets.GHCR_TOKEN }} task docker-push
