name: Publish Docker image to container registry

on:
  push:
    branches:
      - main

env:
  APPNAME: myapiserver

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(git describe --tags --always --dirty="-dev")

    - name: Get the short version
      id: get_version_short
      run: echo ::set-output name=VERSION_SHORT::$(git describe --tags --always --dirty="-dev" --abbrev=0)

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DHCR_USER }}
        password: ${{ secrets.DHCR_TOKEN }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USER }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ secrets.GHCR_USER }}/${{ env.APPNAME }}:${{ steps.get_version.outputs.VERSION }}
          ghcr.io/${{ secrets.GHCR_USER }}/${{ env.APPNAME }}:${{ steps.get_version_short.outputs.VERSION_SHORT }}
          ghcr.io/${{ secrets.GHCR_USER }}/${{ env.APPNAME }}:latest
        build-args: |
          APPNAME=${{ env.APPNAME }}
          VERSION=${{ steps.get_version.outputs.VERSION }}
