# This workflow builds a docker image with the Dev Container CLI
#
name: Publish Docker image to GitHub Container Registry

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-devcontainer:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build base dev container image
      uses: devcontainers/ci@v0.3
      with:
        # Annoying https://github.com/devcontainers/ci/issues/150
        imageName: ghcr.io/${{ github.repository }}-devcontainer
        skipContainerUserIdUpdate: true
        push: always
        runCmd: echo "Image built successfully"

  build-application:
    needs: build-devcontainer
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push docker image using devcontainer
      uses: devcontainers/ci@v0.3
      env:
        GHCR_USER: ${{ github.repository_owner }}
        GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
      with:
        cacheFrom: ghcr.io/${{ github.repository }}-devcontainer
        runCmd: task docker-push
